name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master  # Change this to your default branch if it's different
    # Uncomment the following lines if you want to trigger only when specific paths change
    # paths:
    #   - 'dkutti-serverless/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Define a strategy matrix to test multiple Node.js versions
    strategy:
      matrix:
        node-version: [18.x]  # Specify the Node.js versions to test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        # Use the Node.js version from the matrix
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Uncomment this if your project has dependencies
      # - name: Install dependencies
      #   run: npm install

      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Deploy using Serverless GitHub Action
        uses: serverless/github-action@master
        with:
          args: deploy  # Run `serverless deploy`
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # Specify your AWS region
        #   SLS_DEBUG: '*'
        # working-directory: dkutti-serverless  # Ensure the correct working directory
      # Step to retrieve and display the API Gateway URL
      - name: Get and Display API URL
        run: |
          echo "Fetching API Endpoint URL:"
          serverless info --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1